module.exports.maps = [
            "7 Hours Later II http://www.gamemaps.com/details/2688",
            "A Dam Mission http://www.gamemaps.com/details/5891",
            "Absolute Zero http://www.gamemaps.com/details/2423",
            "Back to School http://www.gamemaps.com/details/6691",
            "Beldurra http://www.gamemaps.com/details/3773",
            "Beldurra II http://www.gamemaps.com/details/8338",
            "Blackout Basement http://www.gamemaps.com/details/3442",
            "Blight Path http://www.gamemaps.com/details/2924",
            "Blood Proof http://www.gamemaps.com/details/3994",
            "Blood Tracks http://www.gamemaps.com/details/2750",
            "Blood Woods: Apocalypse http://www.gamemaps.com/details/9314",
            "Carried Off http://www.gamemaps.com/details/2230",
            "Chaos Theory http://www.gamemaps.com/details/2331",
            "City 17 http://www.gamemaps.com/details/2506",
            "Claustrophobia http://www.gamemaps.com/details/3987",
            "Cold Stream Beta http://www.gamemaps.com/details/16023",
            "Cold Stream Night http://www.gamemaps.com/details/16457",
            "Contact: Remastered http://www.gamemaps.com/details/13992",
            "Crash Bandicoot: Dr. Cortex http://www.gamemaps.com/details/2839",
            "Crash Bandicoot: EW http://www.gamemaps.com/details/2591",
            "Crash Course Enhanced http://www.gamemaps.com/details/3214",
            "Cure II http://www.gamemaps.com/details/16782",
            "Dark Blood II http://www.gamemaps.com/details/2592",
            "Dark Center http://www.gamemaps.com/details/16132",
            "Dark Wood http://www.gamemaps.com/details/14120",
            "Day Break http://www.gamemaps.com/details/9221",
            "Dead Before Dawn http://www.gamemaps.com/details/2268",
            "Dead City II http://www.gamemaps.com/details/2464",
            "Dead Destination http://www.gamemaps.com/details/3027",
            "Dead Echo II http://www.gamemaps.com/details/2518",
            "Dead Flag Blues II http://www.gamemaps.com/details/2136",
            "Dead Getaway http://www.gamemaps.com/details/3305",
            "Dead St. 2 http://www.gamemaps.com/details/8482",
            "Dead Vacation http://www.gamemaps.com/details/16354",
            "Deadbeat Escape http://www.gamemaps.com/details/9304",
            "Deadenator http://steamcommunity.com/sharedfiles/filedetails/?id=672231603",
            "Death Aboard II http://www.gamemaps.com/details/2486",
            "Death From Above http://www.gamemaps.com/details/7036",
            "Death Mountain http://www.gamemaps.com/details/7672",
            "Death Sentence http://www.gamemaps.com/details/2624",
            "Death Strip http://www.gamemaps.com/details/3470",
            "Death Toilet Maze http://www.gamemaps.com/details/16917",
            "Death Trip http://www.gamemaps.com/details/16119",
            "Detour Ahead http://www.gamemaps.com/details/2445",
            "Die Screaming II http://www.gamemaps.com/details/2778",
            "Diescraper Redux http://www.gamemaps.com/details/2413",
            "Dniepr http://www.gamemaps.com/details/15918",
            "Downtown Dine http://www.gamemaps.com/details/9056",
            "Downtown Dine: Dead End http://www.gamemaps.com/details/10071",
            "Drop Dead Gorges http://www.gamemaps.com/details/2135",
            "Energy crisis http://www.gamemaps.com/details/13867",
            "Escansion http://www.gamemaps.com/details/2451",
            "Escape From Valencia http://www.gamemaps.com/details/8798",
            "Fairfield Fallen http://www.gamemaps.com/details/9153",
            "Fall in Death http://www.gamemaps.com/details/2403",
            "Farewell Chenming http://www.gamemaps.com/details/14513",
            "Fatal Freight http://www.gamemaps.com/details/14002",
            "Freezer Burn http://www.gamemaps.com/details/2456",
            "Gas Fever http://www.gamemaps.com/details/2689",
            "GoldenEye 4 Dead http://www.gamemaps.com/details/3198",
            "Gunk http://www.gamemaps.com/details/16952",
            "Half-Life 2: Chapter 1 & 2 http://www.gamemaps.com/details/6629",
            "Half-Life 2: Chapter 3 http://www.gamemaps.com/details/6781",
            "Half-Life 2: Chapter 4 & 5 http://www.gamemaps.com/details/7343",
            "Hard Rain: Downpour http://www.gamemaps.com/details/12237",
            "Haunted Forest http://www.gamemaps.com/details/2653",
            "Heaven Can Wait http://www.gamemaps.com/details/10254",
            "HEM: Blood Harvest http://www.gamemaps.com/details/7986",
            "HEM: Dead Air http://www.gamemaps.com/details/7943",
            "HEM: Death Toll http://www.gamemaps.com/details/7969",
            "HEM: No Mercy http://www.gamemaps.com/details/7989",
            "Highway to Hell http://www.gamemaps.com/details/2714",
            "I Hate Mountains II http://www.gamemaps.com/details/2731",
            "Infected CIty http://www.gamemaps.com/details/3126",
            "Innes Road Rash http://www.gamemaps.com/details/3760",
            "Journey to Splash Mountain http://www.gamemaps.com/details/6084",
            "Last Summer http://www.gamemaps.com/details/4244",
            "Left 4 Duluth http://www.gamemaps.com/details/2818",
            "Left 4 GoldenEye http://www.gamemaps.com/details/3283",
            "Left Behind http://www.gamemaps.com/details/2838",
            "Left in China http://www.gamemaps.com/details/2829",
            "Lost http://www.gamemaps.com/details/14807",
            "Military Industrial Complex II http://www.gamemaps.com/details/2633",
            "Night Terror http://www.gamemaps.com/details/2597",
            "No Space 4 Zombies http://www.gamemaps.com/details/2481",
            "One 4 Nine http://www.gamemaps.com/details/2682",
            "Open Road http://www.gamemaps.com/details/2741",
            "Overkill http://www.gamemaps.com/details/2675",
            "Pitch Dark Mesa http://www.gamemaps.com/details/14745",
            "Plan B http://www.gamemaps.com/details/8732",
            "Precinct 84 http://www.gamemaps.com/details/2476",
            "Project Album II http://www.gamemaps.com/details/4096",
            "Questionable Ethics http://www.gamemaps.com/details/2795",
            "Questionable Ethics: Alpha http://www.gamemaps.com/details/3589",
            "Redemption II http://www.gamemaps.com/details/2849",
            "Resident Evil 3 http://www.gamemaps.com/details/16220",
            "Reverse No Mercy II http://www.gamemaps.com/details/18049",
            "RMS Titanic http://www.gamemaps.com/details/2538",
            "Road to Nowhere II http://www.gamemaps.com/details/3560",
            "Run to the Hills http://www.gamemaps.com/details/2559",
            "Salthell Park http://www.gamemaps.com/details/3418",
            "Shadow Moses Island http://www.gamemaps.com/details/2600",
            "Silent Hill II http://www.gamemaps.com/details/16110",
            "Silent Hill: Otherside of Life http://www.gamemaps.com/details/7592",
            "Stargate SG-4 http://www.gamemaps.com/details/6963",
            "Stenches http://www.gamemaps.com/details/16581",
            "Suicide Blitz II http://www.gamemaps.com/details/2793",
            "Surrounded by Dead II http://www.gamemaps.com/details/2655",
            "Symbyosys http://www.gamemaps.com/details/7949",
            "The Bloody Moors http://www.gamemaps.com/details/6772",
            "The Cure http://www.gamemaps.com/details/11669",
            "The Dark Parish http://www.gamemaps.com/details/3467",
            "The Hive http://www.gamemaps.com/details/11555",
            "The Last Volt http://www.gamemaps.com/details/8313",
            "The Parish Beta http://www.gamemaps.com/details/8117",
            "There is only one way http://www.gamemaps.com/details/5567",
            "Tour of Terror http://www.gamemaps.com/details/2721",
            "True Fangshi http://www.gamemaps.com/details/3078",
            "Two Evil Eyes http://www.gamemaps.com/details/2478",
            "Undead Smackdown http://www.gamemaps.com/details/14590",
            "Undead Zone http://www.gamemaps.com/details/6599",
            "Urban Flight http://www.gamemaps.com/details/2639",
            "Vienna Calling I http://www.gamemaps.com/details/2119",
            "Vienna Calling II http://www.gamemaps.com/details/2719",
            "Wan Li http://www.gamemaps.com/details/2906",
            "Warcelona http://www.gamemaps.com/details/3131",
            "We Don't Go to Ravenholm II http://www.gamemaps.com/details/2531",
            "Welcome to Hell http://www.gamemaps.com/details/2248",
            "White Forest http://www.gamemaps.com/details/16814",
            "Yama http://www.gamemaps.com/details/2850",
            "You Are Doomed http://www.gamemaps.com/details/16353",
            "ZMB-13 http://www.gamemaps.com/details/6846",
            "Left 4 Duluth http://www.gamemaps.com/details/2818",
            "Resident Evil 1 http://www.gamemaps.com/details/15643",
            "Devil Mountain http://www.gamemaps.com/mirrors/9605",
            "DeadSeries http://www.gamemaps.com/details/2701",
];
